### ISSUE TITLE
How to assemble a pillar?

### ISSUE THREAD

**Issue by HyperMan19680** [nflantier/SFA1.5#1]
I'm trying to assemble a multiblock Pillar in this mod, the first one, but I feel I'm missing a certain block needed to activate it. The Basic Hammer isn't helping, nor is the manual.

**Comment by nflantier** [comment]
If you did the structure right you have to right click the highest block of the pillar with a basic hammer set  to basic mode. If you want to be really sure of your structure place down a asgardian block (asgardite block, asgardian steel block, asgardian bronze block ), set your hammer in construction mod ( by shift right click it ) and right click the block it will show you the pillar structure in 3D. To assemble the pillar always set your hammer in basic mode ( by shift right click it ) and right click the highest block of the pillar.

**Comment by HyperMan19680** [comment]
Yeah, I didn't see the part where I had to click the topmost block. But I managed to make it work. Thanks!
